# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Node.js.
environment:
  matrix:
  - PHANTOM_SRC: "npm"
  - PHANTOM_SRC: "chocolatey"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node
  - ps: Install-Product node 0.12
  # Typical npm stuff.
  - md C:\nc
  - npm install -g npm@^2
  # Workaround https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows
  - set PATH=%APPDATA%\npm;%PATH%
  - npm config set cache C:\nc
  - npm version
  - npm install
  # Install PhantomJS
  - IF %PHANTOM_SRC%==npm npm install -g phantomjs
  - IF %PHANTOM_SRC%==chocolatey cinst PhantomJS -Version 1.9.8 -y && set path=%path%;C:\tools\PhantomJS\
  - phantomjs -v

# Post-install test scripts.
test_script:
  - cmd: npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
